fos_ck_editor:
        default_config: short_config
        configs:
            short_config:
                toolbar: [ ["Source", "-", "Save","Paste",'-',
                 "Undo", "Redo","-","Bold","Italic","-",
                  'JustifyLeft','JustifyCenter','JustifyRight',"-",
                   'NumberedList','BulletedList',], "/", ]
            full_config:
                filebrowserUploadUrl: 'ck_upload_img'
                filebrowserUploadMethod: "form"
                filebrowserBrowseRoute: file_manager
                filebrowserBrowseRouteParameters:
                    conf: files
                    module: ckeditor
                filebrowserImageBrowseRoute: file_manager
                filebrowserImageBrowseRouteParameters:
                    conf: images
                    module: ckeditor
                uiColor: "#f0ffff"
               # ...